/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthTrashRouteImport } from './routes/_auth/trash'
import { Route as AuthTrackingRouteImport } from './routes/_auth/tracking'
import { Route as AuthStocksRouteImport } from './routes/_auth/stocks'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSessionsRouteImport } from './routes/_auth/sessions'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthHabitsRouteImport } from './routes/_auth/habits'
import { Route as AuthStatsIndexRouteImport } from './routes/_auth/stats/index'
import { Route as AuthWorkoutExerciseLibraryRouteImport } from './routes/_auth/workout/exercise-library'
import { Route as AuthTrackingRecurringRouteImport } from './routes/_auth/tracking/recurring'
import { Route as AuthTrackingJournalRouteImport } from './routes/_auth/tracking/journal'
import { Route as AuthTrackingEventsRouteImport } from './routes/_auth/tracking/events'
import { Route as AuthStocksShoppingRouteImport } from './routes/_auth/stocks/shopping'
import { Route as AuthStocksRoutinesRouteImport } from './routes/_auth/stocks/routines'
import { Route as AuthStocksInventoryRouteImport } from './routes/_auth/stocks/inventory'
import { Route as AuthStatsWorkoutRouteImport } from './routes/_auth/stats/workout'
import { Route as AuthStatsWorkRouteImport } from './routes/_auth/stats/work'
import { Route as AuthStatsStocksRouteImport } from './routes/_auth/stats/stocks'
import { Route as AuthStatsRecurringRouteImport } from './routes/_auth/stats/recurring'
import { Route as AuthStatsJournalRouteImport } from './routes/_auth/stats/journal'
import { Route as AuthStatsHabitsRouteImport } from './routes/_auth/stats/habits'
import { Route as AuthStatsEventsRouteImport } from './routes/_auth/stats/events'
import { Route as AuthStatsCardioRouteImport } from './routes/_auth/stats/cardio'
import { Route as AuthSessionsWorkoutRouteImport } from './routes/_auth/sessions/workout'
import { Route as AuthSessionsWorkRouteImport } from './routes/_auth/sessions/work'
import { Route as AuthSessionsCardioRouteImport } from './routes/_auth/sessions/cardio'
import { Route as AuthSessionsWorkoutIndexRouteImport } from './routes/_auth/sessions/workout/index'
import { Route as AuthSessionsWorkoutProgramsRouteImport } from './routes/_auth/sessions/workout/programs'
import { Route as AuthSessionsWorkoutHistoryRouteImport } from './routes/_auth/sessions/workout/history'
import { Route as AuthSessionsWorkoutProgramsIndexRouteImport } from './routes/_auth/sessions/workout/programs.index'
import { Route as AuthSessionsWorkoutProgramsProgramIdRouteImport } from './routes/_auth/sessions/workout/programs.$programId'
import { Route as AuthSessionsWorkoutLiveSessionTemplateIdRouteImport } from './routes/_auth/sessions/workout/live.$sessionTemplateId'
import { Route as AuthSessionsWorkoutSessionIdEditRouteImport } from './routes/_auth/sessions/workout/$sessionId.edit'
import { Route as AuthSessionsWorkoutExercisesRouteImport } from './routes/_auth/sessions/workout/exercises'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTrashRoute = AuthTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrackingRoute = AuthTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStocksRoute = AuthStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHabitsRoute = AuthHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsIndexRoute = AuthStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkoutExerciseLibraryRoute =
  AuthWorkoutExerciseLibraryRouteImport.update({
    id: '/workout/exercise-library',
    path: '/workout/exercise-library',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTrackingRecurringRoute = AuthTrackingRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AuthTrackingRoute,
} as any)
const AuthTrackingJournalRoute = AuthTrackingJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthTrackingRoute,
} as any)
const AuthTrackingEventsRoute = AuthTrackingEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthTrackingRoute,
} as any)
const AuthStocksShoppingRoute = AuthStocksShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthStocksRoute,
} as any)
const AuthStocksRoutinesRoute = AuthStocksRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthStocksRoute,
} as any)
const AuthStocksInventoryRoute = AuthStocksInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthStocksRoute,
} as any)
const AuthStatsWorkoutRoute = AuthStatsWorkoutRouteImport.update({
  id: '/stats/workout',
  path: '/stats/workout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsWorkRoute = AuthStatsWorkRouteImport.update({
  id: '/stats/work',
  path: '/stats/work',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsStocksRoute = AuthStatsStocksRouteImport.update({
  id: '/stats/stocks',
  path: '/stats/stocks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsRecurringRoute = AuthStatsRecurringRouteImport.update({
  id: '/stats/recurring',
  path: '/stats/recurring',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsJournalRoute = AuthStatsJournalRouteImport.update({
  id: '/stats/journal',
  path: '/stats/journal',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsHabitsRoute = AuthStatsHabitsRouteImport.update({
  id: '/stats/habits',
  path: '/stats/habits',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsEventsRoute = AuthStatsEventsRouteImport.update({
  id: '/stats/events',
  path: '/stats/events',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsCardioRoute = AuthStatsCardioRouteImport.update({
  id: '/stats/cardio',
  path: '/stats/cardio',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsWorkoutRoute = AuthSessionsWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthSessionsRoute,
} as any)
const AuthSessionsWorkRoute = AuthSessionsWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthSessionsRoute,
} as any)
const AuthSessionsCardioRoute = AuthSessionsCardioRouteImport.update({
  id: '/cardio',
  path: '/cardio',
  getParentRoute: () => AuthSessionsRoute,
} as any)
const AuthSessionsWorkoutIndexRoute =
  AuthSessionsWorkoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSessionsWorkoutRoute,
  } as any)
const AuthSessionsWorkoutProgramsRoute =
  AuthSessionsWorkoutProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthSessionsWorkoutRoute,
  } as any)
const AuthSessionsWorkoutHistoryRoute =
  AuthSessionsWorkoutHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthSessionsWorkoutRoute,
  } as any)
const AuthSessionsWorkoutProgramsIndexRoute =
  AuthSessionsWorkoutProgramsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSessionsWorkoutProgramsRoute,
  } as any)
const AuthSessionsWorkoutProgramsProgramIdRoute =
  AuthSessionsWorkoutProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => AuthSessionsWorkoutProgramsRoute,
  } as any)
const AuthSessionsWorkoutLiveSessionTemplateIdRoute =
  AuthSessionsWorkoutLiveSessionTemplateIdRouteImport.update({
    id: '/live/$sessionTemplateId',
    path: '/live/$sessionTemplateId',
    getParentRoute: () => AuthSessionsWorkoutRoute,
  } as any)
const AuthSessionsWorkoutSessionIdEditRoute =
  AuthSessionsWorkoutSessionIdEditRouteImport.update({
    id: '/$sessionId/edit',
    path: '/$sessionId/edit',
    getParentRoute: () => AuthSessionsWorkoutRoute,
  } as any)
const AuthSessionsWorkoutExercisesRoute =
  AuthSessionsWorkoutExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthSessionsWorkoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/habits': typeof AuthHabitsRoute
  '/projects': typeof AuthProjectsRoute
  '/sessions': typeof AuthSessionsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/stocks': typeof AuthStocksRouteWithChildren
  '/tracking': typeof AuthTrackingRouteWithChildren
  '/trash': typeof AuthTrashRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sessions/cardio': typeof AuthSessionsCardioRoute
  '/sessions/work': typeof AuthSessionsWorkRoute
  '/sessions/workout': typeof AuthSessionsWorkoutRouteWithChildren
  '/stats/cardio': typeof AuthStatsCardioRoute
  '/stats/events': typeof AuthStatsEventsRoute
  '/stats/habits': typeof AuthStatsHabitsRoute
  '/stats/journal': typeof AuthStatsJournalRoute
  '/stats/recurring': typeof AuthStatsRecurringRoute
  '/stats/stocks': typeof AuthStatsStocksRoute
  '/stats/work': typeof AuthStatsWorkRoute
  '/stats/workout': typeof AuthStatsWorkoutRoute
  '/stocks/inventory': typeof AuthStocksInventoryRoute
  '/stocks/routines': typeof AuthStocksRoutinesRoute
  '/stocks/shopping': typeof AuthStocksShoppingRoute
  '/tracking/events': typeof AuthTrackingEventsRoute
  '/tracking/journal': typeof AuthTrackingJournalRoute
  '/tracking/recurring': typeof AuthTrackingRecurringRoute
  '/workout/exercise-library': typeof AuthWorkoutExerciseLibraryRoute
  '/stats/': typeof AuthStatsIndexRoute
  '/sessions/workout/history': typeof AuthSessionsWorkoutHistoryRoute
  '/sessions/workout/programs': typeof AuthSessionsWorkoutProgramsRouteWithChildren
  '/sessions/workout/': typeof AuthSessionsWorkoutIndexRoute
  '/sessions/workout/$sessionId/edit': typeof AuthSessionsWorkoutSessionIdEditRoute
  '/sessions/workout/live/$sessionTemplateId': typeof AuthSessionsWorkoutLiveSessionTemplateIdRoute
  '/sessions/workout/programs/$programId': typeof AuthSessionsWorkoutProgramsProgramIdRoute
  '/sessions/workout/programs/': typeof AuthSessionsWorkoutProgramsIndexRoute
  '/sessions/workout/exercises': typeof AuthSessionsWorkoutExercisesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/habits': typeof AuthHabitsRoute
  '/projects': typeof AuthProjectsRoute
  '/sessions': typeof AuthSessionsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/stocks': typeof AuthStocksRouteWithChildren
  '/tracking': typeof AuthTrackingRouteWithChildren
  '/trash': typeof AuthTrashRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthIndexRoute
  '/sessions/cardio': typeof AuthSessionsCardioRoute
  '/sessions/work': typeof AuthSessionsWorkRoute
  '/stats/cardio': typeof AuthStatsCardioRoute
  '/stats/events': typeof AuthStatsEventsRoute
  '/stats/habits': typeof AuthStatsHabitsRoute
  '/stats/journal': typeof AuthStatsJournalRoute
  '/stats/recurring': typeof AuthStatsRecurringRoute
  '/stats/stocks': typeof AuthStatsStocksRoute
  '/stats/work': typeof AuthStatsWorkRoute
  '/stats/workout': typeof AuthStatsWorkoutRoute
  '/stocks/inventory': typeof AuthStocksInventoryRoute
  '/stocks/routines': typeof AuthStocksRoutinesRoute
  '/stocks/shopping': typeof AuthStocksShoppingRoute
  '/tracking/events': typeof AuthTrackingEventsRoute
  '/tracking/journal': typeof AuthTrackingJournalRoute
  '/tracking/recurring': typeof AuthTrackingRecurringRoute
  '/workout/exercise-library': typeof AuthWorkoutExerciseLibraryRoute
  '/stats': typeof AuthStatsIndexRoute
  '/sessions/workout/history': typeof AuthSessionsWorkoutHistoryRoute
  '/sessions/workout': typeof AuthSessionsWorkoutIndexRoute
  '/sessions/workout/$sessionId/edit': typeof AuthSessionsWorkoutSessionIdEditRoute
  '/sessions/workout/live/$sessionTemplateId': typeof AuthSessionsWorkoutLiveSessionTemplateIdRoute
  '/sessions/workout/programs/$programId': typeof AuthSessionsWorkoutProgramsProgramIdRoute
  '/sessions/workout/programs': typeof AuthSessionsWorkoutProgramsIndexRoute
  '/sessions/workout/exercises': typeof AuthSessionsWorkoutExercisesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/habits': typeof AuthHabitsRoute
  '/_auth/projects': typeof AuthProjectsRoute
  '/_auth/sessions': typeof AuthSessionsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/stocks': typeof AuthStocksRouteWithChildren
  '/_auth/tracking': typeof AuthTrackingRouteWithChildren
  '/_auth/trash': typeof AuthTrashRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/sessions/cardio': typeof AuthSessionsCardioRoute
  '/_auth/sessions/work': typeof AuthSessionsWorkRoute
  '/_auth/sessions/workout': typeof AuthSessionsWorkoutRouteWithChildren
  '/_auth/stats/cardio': typeof AuthStatsCardioRoute
  '/_auth/stats/events': typeof AuthStatsEventsRoute
  '/_auth/stats/habits': typeof AuthStatsHabitsRoute
  '/_auth/stats/journal': typeof AuthStatsJournalRoute
  '/_auth/stats/recurring': typeof AuthStatsRecurringRoute
  '/_auth/stats/stocks': typeof AuthStatsStocksRoute
  '/_auth/stats/work': typeof AuthStatsWorkRoute
  '/_auth/stats/workout': typeof AuthStatsWorkoutRoute
  '/_auth/stocks/inventory': typeof AuthStocksInventoryRoute
  '/_auth/stocks/routines': typeof AuthStocksRoutinesRoute
  '/_auth/stocks/shopping': typeof AuthStocksShoppingRoute
  '/_auth/tracking/events': typeof AuthTrackingEventsRoute
  '/_auth/tracking/journal': typeof AuthTrackingJournalRoute
  '/_auth/tracking/recurring': typeof AuthTrackingRecurringRoute
  '/_auth/workout/exercise-library': typeof AuthWorkoutExerciseLibraryRoute
  '/_auth/stats/': typeof AuthStatsIndexRoute
  '/_auth/sessions/workout/history': typeof AuthSessionsWorkoutHistoryRoute
  '/_auth/sessions/workout/programs': typeof AuthSessionsWorkoutProgramsRouteWithChildren
  '/_auth/sessions/workout/': typeof AuthSessionsWorkoutIndexRoute
  '/_auth/sessions/workout/$sessionId/edit': typeof AuthSessionsWorkoutSessionIdEditRoute
  '/_auth/sessions/workout/live/$sessionTemplateId': typeof AuthSessionsWorkoutLiveSessionTemplateIdRoute
  '/_auth/sessions/workout/programs/$programId': typeof AuthSessionsWorkoutProgramsProgramIdRoute
  '/_auth/sessions/workout/programs/': typeof AuthSessionsWorkoutProgramsIndexRoute
  '/_auth/sessions/workout/exercises': typeof AuthSessionsWorkoutExercisesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/habits'
    | '/projects'
    | '/sessions'
    | '/settings'
    | '/stocks'
    | '/tracking'
    | '/trash'
    | '/auth/callback'
    | '/sessions/cardio'
    | '/sessions/work'
    | '/sessions/workout'
    | '/stats/cardio'
    | '/stats/events'
    | '/stats/habits'
    | '/stats/journal'
    | '/stats/recurring'
    | '/stats/stocks'
    | '/stats/work'
    | '/stats/workout'
    | '/stocks/inventory'
    | '/stocks/routines'
    | '/stocks/shopping'
    | '/tracking/events'
    | '/tracking/journal'
    | '/tracking/recurring'
    | '/workout/exercise-library'
    | '/stats/'
    | '/sessions/workout/history'
    | '/sessions/workout/programs'
    | '/sessions/workout/'
    | '/sessions/workout/$sessionId/edit'
    | '/sessions/workout/live/$sessionTemplateId'
    | '/sessions/workout/programs/$programId'
    | '/sessions/workout/programs/'
    | '/sessions/workout/exercises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/habits'
    | '/projects'
    | '/sessions'
    | '/settings'
    | '/stocks'
    | '/tracking'
    | '/trash'
    | '/auth/callback'
    | '/'
    | '/sessions/cardio'
    | '/sessions/work'
    | '/stats/cardio'
    | '/stats/events'
    | '/stats/habits'
    | '/stats/journal'
    | '/stats/recurring'
    | '/stats/stocks'
    | '/stats/work'
    | '/stats/workout'
    | '/stocks/inventory'
    | '/stocks/routines'
    | '/stocks/shopping'
    | '/tracking/events'
    | '/tracking/journal'
    | '/tracking/recurring'
    | '/workout/exercise-library'
    | '/stats'
    | '/sessions/workout/history'
    | '/sessions/workout'
    | '/sessions/workout/$sessionId/edit'
    | '/sessions/workout/live/$sessionTemplateId'
    | '/sessions/workout/programs/$programId'
    | '/sessions/workout/programs'
    | '/sessions/workout/exercises'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/habits'
    | '/_auth/projects'
    | '/_auth/sessions'
    | '/_auth/settings'
    | '/_auth/stocks'
    | '/_auth/tracking'
    | '/_auth/trash'
    | '/auth/callback'
    | '/_auth/'
    | '/_auth/sessions/cardio'
    | '/_auth/sessions/work'
    | '/_auth/sessions/workout'
    | '/_auth/stats/cardio'
    | '/_auth/stats/events'
    | '/_auth/stats/habits'
    | '/_auth/stats/journal'
    | '/_auth/stats/recurring'
    | '/_auth/stats/stocks'
    | '/_auth/stats/work'
    | '/_auth/stats/workout'
    | '/_auth/stocks/inventory'
    | '/_auth/stocks/routines'
    | '/_auth/stocks/shopping'
    | '/_auth/tracking/events'
    | '/_auth/tracking/journal'
    | '/_auth/tracking/recurring'
    | '/_auth/workout/exercise-library'
    | '/_auth/stats/'
    | '/_auth/sessions/workout/history'
    | '/_auth/sessions/workout/programs'
    | '/_auth/sessions/workout/'
    | '/_auth/sessions/workout/$sessionId/edit'
    | '/_auth/sessions/workout/live/$sessionTemplateId'
    | '/_auth/sessions/workout/programs/$programId'
    | '/_auth/sessions/workout/programs/'
    | '/_auth/sessions/workout/exercises'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/trash': {
      id: '/_auth/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthTrashRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tracking': {
      id: '/_auth/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthTrackingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stocks': {
      id: '/_auth/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthStocksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions': {
      id: '/_auth/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthSessionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/habits': {
      id: '/_auth/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthHabitsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/': {
      id: '/_auth/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof AuthStatsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workout/exercise-library': {
      id: '/_auth/workout/exercise-library'
      path: '/workout/exercise-library'
      fullPath: '/workout/exercise-library'
      preLoaderRoute: typeof AuthWorkoutExerciseLibraryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tracking/recurring': {
      id: '/_auth/tracking/recurring'
      path: '/recurring'
      fullPath: '/tracking/recurring'
      preLoaderRoute: typeof AuthTrackingRecurringRouteImport
      parentRoute: typeof AuthTrackingRoute
    }
    '/_auth/tracking/journal': {
      id: '/_auth/tracking/journal'
      path: '/journal'
      fullPath: '/tracking/journal'
      preLoaderRoute: typeof AuthTrackingJournalRouteImport
      parentRoute: typeof AuthTrackingRoute
    }
    '/_auth/tracking/events': {
      id: '/_auth/tracking/events'
      path: '/events'
      fullPath: '/tracking/events'
      preLoaderRoute: typeof AuthTrackingEventsRouteImport
      parentRoute: typeof AuthTrackingRoute
    }
    '/_auth/stocks/shopping': {
      id: '/_auth/stocks/shopping'
      path: '/shopping'
      fullPath: '/stocks/shopping'
      preLoaderRoute: typeof AuthStocksShoppingRouteImport
      parentRoute: typeof AuthStocksRoute
    }
    '/_auth/stocks/routines': {
      id: '/_auth/stocks/routines'
      path: '/routines'
      fullPath: '/stocks/routines'
      preLoaderRoute: typeof AuthStocksRoutinesRouteImport
      parentRoute: typeof AuthStocksRoute
    }
    '/_auth/stocks/inventory': {
      id: '/_auth/stocks/inventory'
      path: '/inventory'
      fullPath: '/stocks/inventory'
      preLoaderRoute: typeof AuthStocksInventoryRouteImport
      parentRoute: typeof AuthStocksRoute
    }
    '/_auth/stats/workout': {
      id: '/_auth/stats/workout'
      path: '/stats/workout'
      fullPath: '/stats/workout'
      preLoaderRoute: typeof AuthStatsWorkoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/work': {
      id: '/_auth/stats/work'
      path: '/stats/work'
      fullPath: '/stats/work'
      preLoaderRoute: typeof AuthStatsWorkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/stocks': {
      id: '/_auth/stats/stocks'
      path: '/stats/stocks'
      fullPath: '/stats/stocks'
      preLoaderRoute: typeof AuthStatsStocksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/recurring': {
      id: '/_auth/stats/recurring'
      path: '/stats/recurring'
      fullPath: '/stats/recurring'
      preLoaderRoute: typeof AuthStatsRecurringRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/journal': {
      id: '/_auth/stats/journal'
      path: '/stats/journal'
      fullPath: '/stats/journal'
      preLoaderRoute: typeof AuthStatsJournalRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/habits': {
      id: '/_auth/stats/habits'
      path: '/stats/habits'
      fullPath: '/stats/habits'
      preLoaderRoute: typeof AuthStatsHabitsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/events': {
      id: '/_auth/stats/events'
      path: '/stats/events'
      fullPath: '/stats/events'
      preLoaderRoute: typeof AuthStatsEventsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/cardio': {
      id: '/_auth/stats/cardio'
      path: '/stats/cardio'
      fullPath: '/stats/cardio'
      preLoaderRoute: typeof AuthStatsCardioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/workout': {
      id: '/_auth/sessions/workout'
      path: '/workout'
      fullPath: '/sessions/workout'
      preLoaderRoute: typeof AuthSessionsWorkoutRouteImport
      parentRoute: typeof AuthSessionsRoute
    }
    '/_auth/sessions/work': {
      id: '/_auth/sessions/work'
      path: '/work'
      fullPath: '/sessions/work'
      preLoaderRoute: typeof AuthSessionsWorkRouteImport
      parentRoute: typeof AuthSessionsRoute
    }
    '/_auth/sessions/cardio': {
      id: '/_auth/sessions/cardio'
      path: '/cardio'
      fullPath: '/sessions/cardio'
      preLoaderRoute: typeof AuthSessionsCardioRouteImport
      parentRoute: typeof AuthSessionsRoute
    }
    '/_auth/sessions/workout/': {
      id: '/_auth/sessions/workout/'
      path: '/'
      fullPath: '/sessions/workout/'
      preLoaderRoute: typeof AuthSessionsWorkoutIndexRouteImport
      parentRoute: typeof AuthSessionsWorkoutRoute
    }
    '/_auth/sessions/workout/programs': {
      id: '/_auth/sessions/workout/programs'
      path: '/programs'
      fullPath: '/sessions/workout/programs'
      preLoaderRoute: typeof AuthSessionsWorkoutProgramsRouteImport
      parentRoute: typeof AuthSessionsWorkoutRoute
    }
    '/_auth/sessions/workout/history': {
      id: '/_auth/sessions/workout/history'
      path: '/history'
      fullPath: '/sessions/workout/history'
      preLoaderRoute: typeof AuthSessionsWorkoutHistoryRouteImport
      parentRoute: typeof AuthSessionsWorkoutRoute
    }
    '/_auth/sessions/workout/programs/': {
      id: '/_auth/sessions/workout/programs/'
      path: '/'
      fullPath: '/sessions/workout/programs/'
      preLoaderRoute: typeof AuthSessionsWorkoutProgramsIndexRouteImport
      parentRoute: typeof AuthSessionsWorkoutProgramsRoute
    }
    '/_auth/sessions/workout/programs/$programId': {
      id: '/_auth/sessions/workout/programs/$programId'
      path: '/$programId'
      fullPath: '/sessions/workout/programs/$programId'
      preLoaderRoute: typeof AuthSessionsWorkoutProgramsProgramIdRouteImport
      parentRoute: typeof AuthSessionsWorkoutProgramsRoute
    }
    '/_auth/sessions/workout/live/$sessionTemplateId': {
      id: '/_auth/sessions/workout/live/$sessionTemplateId'
      path: '/live/$sessionTemplateId'
      fullPath: '/sessions/workout/live/$sessionTemplateId'
      preLoaderRoute: typeof AuthSessionsWorkoutLiveSessionTemplateIdRouteImport
      parentRoute: typeof AuthSessionsWorkoutRoute
    }
    '/_auth/sessions/workout/$sessionId/edit': {
      id: '/_auth/sessions/workout/$sessionId/edit'
      path: '/$sessionId/edit'
      fullPath: '/sessions/workout/$sessionId/edit'
      preLoaderRoute: typeof AuthSessionsWorkoutSessionIdEditRouteImport
      parentRoute: typeof AuthSessionsWorkoutRoute
    }
    '/_auth/sessions/workout/exercises': {
      id: '/_auth/sessions/workout/exercises'
      path: '/exercises'
      fullPath: '/sessions/workout/exercises'
      preLoaderRoute: typeof AuthSessionsWorkoutExercisesRouteImport
      parentRoute: typeof AuthSessionsWorkoutRoute
    }
  }
}

interface AuthSessionsWorkoutProgramsRouteChildren {
  AuthSessionsWorkoutProgramsProgramIdRoute: typeof AuthSessionsWorkoutProgramsProgramIdRoute
  AuthSessionsWorkoutProgramsIndexRoute: typeof AuthSessionsWorkoutProgramsIndexRoute
}

const AuthSessionsWorkoutProgramsRouteChildren: AuthSessionsWorkoutProgramsRouteChildren =
  {
    AuthSessionsWorkoutProgramsProgramIdRoute:
      AuthSessionsWorkoutProgramsProgramIdRoute,
    AuthSessionsWorkoutProgramsIndexRoute:
      AuthSessionsWorkoutProgramsIndexRoute,
  }

const AuthSessionsWorkoutProgramsRouteWithChildren =
  AuthSessionsWorkoutProgramsRoute._addFileChildren(
    AuthSessionsWorkoutProgramsRouteChildren,
  )

interface AuthSessionsWorkoutRouteChildren {
  AuthSessionsWorkoutHistoryRoute: typeof AuthSessionsWorkoutHistoryRoute
  AuthSessionsWorkoutProgramsRoute: typeof AuthSessionsWorkoutProgramsRouteWithChildren
  AuthSessionsWorkoutIndexRoute: typeof AuthSessionsWorkoutIndexRoute
  AuthSessionsWorkoutSessionIdEditRoute: typeof AuthSessionsWorkoutSessionIdEditRoute
  AuthSessionsWorkoutLiveSessionTemplateIdRoute: typeof AuthSessionsWorkoutLiveSessionTemplateIdRoute
  AuthSessionsWorkoutExercisesRoute: typeof AuthSessionsWorkoutExercisesRoute
}

const AuthSessionsWorkoutRouteChildren: AuthSessionsWorkoutRouteChildren = {
  AuthSessionsWorkoutHistoryRoute: AuthSessionsWorkoutHistoryRoute,
  AuthSessionsWorkoutProgramsRoute:
    AuthSessionsWorkoutProgramsRouteWithChildren,
  AuthSessionsWorkoutIndexRoute: AuthSessionsWorkoutIndexRoute,
  AuthSessionsWorkoutSessionIdEditRoute: AuthSessionsWorkoutSessionIdEditRoute,
  AuthSessionsWorkoutLiveSessionTemplateIdRoute:
    AuthSessionsWorkoutLiveSessionTemplateIdRoute,
  AuthSessionsWorkoutExercisesRoute: AuthSessionsWorkoutExercisesRoute,
}

const AuthSessionsWorkoutRouteWithChildren =
  AuthSessionsWorkoutRoute._addFileChildren(AuthSessionsWorkoutRouteChildren)

interface AuthSessionsRouteChildren {
  AuthSessionsCardioRoute: typeof AuthSessionsCardioRoute
  AuthSessionsWorkRoute: typeof AuthSessionsWorkRoute
  AuthSessionsWorkoutRoute: typeof AuthSessionsWorkoutRouteWithChildren
}

const AuthSessionsRouteChildren: AuthSessionsRouteChildren = {
  AuthSessionsCardioRoute: AuthSessionsCardioRoute,
  AuthSessionsWorkRoute: AuthSessionsWorkRoute,
  AuthSessionsWorkoutRoute: AuthSessionsWorkoutRouteWithChildren,
}

const AuthSessionsRouteWithChildren = AuthSessionsRoute._addFileChildren(
  AuthSessionsRouteChildren,
)

interface AuthStocksRouteChildren {
  AuthStocksInventoryRoute: typeof AuthStocksInventoryRoute
  AuthStocksRoutinesRoute: typeof AuthStocksRoutinesRoute
  AuthStocksShoppingRoute: typeof AuthStocksShoppingRoute
}

const AuthStocksRouteChildren: AuthStocksRouteChildren = {
  AuthStocksInventoryRoute: AuthStocksInventoryRoute,
  AuthStocksRoutinesRoute: AuthStocksRoutinesRoute,
  AuthStocksShoppingRoute: AuthStocksShoppingRoute,
}

const AuthStocksRouteWithChildren = AuthStocksRoute._addFileChildren(
  AuthStocksRouteChildren,
)

interface AuthTrackingRouteChildren {
  AuthTrackingEventsRoute: typeof AuthTrackingEventsRoute
  AuthTrackingJournalRoute: typeof AuthTrackingJournalRoute
  AuthTrackingRecurringRoute: typeof AuthTrackingRecurringRoute
}

const AuthTrackingRouteChildren: AuthTrackingRouteChildren = {
  AuthTrackingEventsRoute: AuthTrackingEventsRoute,
  AuthTrackingJournalRoute: AuthTrackingJournalRoute,
  AuthTrackingRecurringRoute: AuthTrackingRecurringRoute,
}

const AuthTrackingRouteWithChildren = AuthTrackingRoute._addFileChildren(
  AuthTrackingRouteChildren,
)

interface AuthRouteChildren {
  AuthHabitsRoute: typeof AuthHabitsRoute
  AuthProjectsRoute: typeof AuthProjectsRoute
  AuthSessionsRoute: typeof AuthSessionsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthStocksRoute: typeof AuthStocksRouteWithChildren
  AuthTrackingRoute: typeof AuthTrackingRouteWithChildren
  AuthTrashRoute: typeof AuthTrashRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthStatsCardioRoute: typeof AuthStatsCardioRoute
  AuthStatsEventsRoute: typeof AuthStatsEventsRoute
  AuthStatsHabitsRoute: typeof AuthStatsHabitsRoute
  AuthStatsJournalRoute: typeof AuthStatsJournalRoute
  AuthStatsRecurringRoute: typeof AuthStatsRecurringRoute
  AuthStatsStocksRoute: typeof AuthStatsStocksRoute
  AuthStatsWorkRoute: typeof AuthStatsWorkRoute
  AuthStatsWorkoutRoute: typeof AuthStatsWorkoutRoute
  AuthWorkoutExerciseLibraryRoute: typeof AuthWorkoutExerciseLibraryRoute
  AuthStatsIndexRoute: typeof AuthStatsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHabitsRoute: AuthHabitsRoute,
  AuthProjectsRoute: AuthProjectsRoute,
  AuthSessionsRoute: AuthSessionsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthStocksRoute: AuthStocksRouteWithChildren,
  AuthTrackingRoute: AuthTrackingRouteWithChildren,
  AuthTrashRoute: AuthTrashRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthStatsCardioRoute: AuthStatsCardioRoute,
  AuthStatsEventsRoute: AuthStatsEventsRoute,
  AuthStatsHabitsRoute: AuthStatsHabitsRoute,
  AuthStatsJournalRoute: AuthStatsJournalRoute,
  AuthStatsRecurringRoute: AuthStatsRecurringRoute,
  AuthStatsStocksRoute: AuthStatsStocksRoute,
  AuthStatsWorkRoute: AuthStatsWorkRoute,
  AuthStatsWorkoutRoute: AuthStatsWorkoutRoute,
  AuthWorkoutExerciseLibraryRoute: AuthWorkoutExerciseLibraryRoute,
  AuthStatsIndexRoute: AuthStatsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
